<a href="https://colab.research.google.com/github/saabir2003/Digit-Recognizer/blob/main/digit_reconization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf


In [ ]:
data=pd.read_csv('train.csv')

In [ ]:
data.describe()

label   pixel0   pixel1   pixel2   pixel3   pixel4   pixel5  \
count  42000.000000  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0   
mean       4.456643      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.887730      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel6   pixel7   pixel8  ...      pixel774      pixel775  \
count  42000.0  42000.0  42000.0  ...  42000.000000  42000.000000   
mean       0.0      0.0      0.0  ...      0.219286      0.117095   
std        0.0      0.0      0.0  ...      6.312890      4.633819   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

           pixel776     pixel777      pixel778      pixel779  pixel780  \
count  42000.000000  42000.00000  42000.000000  42000.000000   42000.0   
mean       0.059024      0.02019      0.017238      0.002857       0.0   
std        3.274488      1.75987      1.894498      0.414264       0.0   
min        0.000000      0.00000      0.000000      0.000000       0.0   
25%        0.000000      0.00000      0.000000      0.000000       0.0   
50%        0.000000      0.00000      0.000000      0.000000       0.0   
75%        0.000000      0.00000      0.000000      0.000000       0.0   
max      253.000000    253.00000    254.000000     62.000000       0.0   

       pixel781  pixel782  pixel783  
count   42000.0   42000.0   42000.0  
mean        0.0       0.0       0.0  
std         0.0       0.0       0.0  
min         0.0       0.0       0.0  
25%         0.0       0.0       0.0  
50%         0.0       0.0       0.0  
75%         0.0       0.0       0.0  
max         0.0       0.0       0.0  

[8 rows x 785 columns]

In [ ]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
X_train=data.drop(columns=['label'])
y_train=data['label']

In [ ]:
print(X_train)
print(y_train)

       pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995       0       0       0       0       0       0       0       0       0   
41996       0       0       0       0       0       0       0       0       0   
41997       0       0       0       0       0       0       0       0       0   
41998       0       0       0       0       0       0       0       0       0   
41999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel77

In [ ]:
tf.random.set_seed(32)


In [ ]:
#normalizing data
X_train=X_train/255

In [ ]:
X_train.describe()

pixel0   pixel1   pixel2   pixel3   pixel4   pixel5   pixel6   pixel7  \
count  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0   
mean       0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
std        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
25%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
50%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
75%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
max        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel8   pixel9  ...      pixel774      pixel775      pixel776  \
count  42000.0  42000.0  ...  42000.000000  42000.000000  42000.000000   
mean       0.0      0.0  ...      0.000860      0.000459      0.000231   
std        0.0      0.0  ...      0.024756      0.018172      0.012841   
min        0.0      0.0  ...      0.000000      0.000000      0.000000   
25%        0.0      0.0  ...      0.000000      0.000000      0.000000   
50%        0.0      0.0  ...      0.000000      0.000000      0.000000   
75%        0.0      0.0  ...      0.000000      0.000000      0.000000   
max        0.0      0.0  ...      0.996078      0.996078      0.992157   

           pixel777      pixel778      pixel779  pixel780  pixel781  pixel782  \
count  42000.000000  42000.000000  42000.000000   42000.0   42000.0   42000.0   
mean       0.000079      0.000068      0.000011       0.0       0.0       0.0   
std        0.006901      0.007429      0.001625       0.0       0.0       0.0   
min        0.000000      0.000000      0.000000       0.0       0.0       0.0   
25%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
50%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
75%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
max        0.992157      0.996078      0.243137       0.0       0.0       0.0   

       pixel783  
count   42000.0  
mean        0.0  
std         0.0  
min         0.0  
25%         0.0  
50%         0.0  
75%         0.0  
max         0.0  

[8 rows x 784 columns]

In [ ]:
X_train

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
41996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
41997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
41998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
41999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0         0.0  ...       0.0       0.0       0.0       0.0       0.0   
1         0.0  ...       0.0       0.0       0.0       0.0       0.0   
2         0.0  ...       0.0       0.0       0.0       0.0       0.0   
3         0.0  ...       0.0       0.0       0.0       0.0       0.0   
4         0.0  ...       0.0       0.0       0.0       0.0       0.0   
...       ...  ...       ...       ...       ...       ...       ...   
41995     0.0  ...       0.0       0.0       0.0       0.0       0.0   
41996     0.0  ...       0.0       0.0       0.0       0.0       0.0   
41997     0.0  ...       0.0       0.0       0.0       0.0       0.0   
41998     0.0  ...       0.0       0.0       0.0       0.0       0.0   
41999     0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0           0.0       0.0       0.0       0.0       0.0  
1           0.0       0.0       0.0       0.0       0.0  
2           0.0       0.0       0.0       0.0       0.0  
3           0.0       0.0       0.0       0.0       0.0  
4           0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
41995       0.0       0.0       0.0       0.0       0.0  
41996       0.0       0.0       0.0       0.0       0.0  
41997       0.0       0.0       0.0       0.0       0.0  
41998       0.0       0.0       0.0       0.0       0.0  
41999       0.0       0.0       0.0       0.0       0.0  

[42000 rows x 784 columns]

In [ ]:
from google.colab import files
X_train.to_csv("X_train.csv")
files.download('X_train.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
tf.random.set_seed(32)

In [ ]:
model1=tf.keras.Sequential([
    tf.keras.layers.Dense(100,activation="relu"),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10,activation='softmax')]
)

model1.compile(optimizer='Adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])


In [ ]:
history1=model1.fit(X_train,y_train,epochs=25)

Epoch 1/25
1313/1313 [==============================] - 6s 4ms/step - loss: 0.2813 - accuracy: 0.9168
Epoch 2/25
1313/1313 [==============================] - 5s 4ms/step - loss: 0.1195 - accuracy: 0.9631
Epoch 3/25
1313/1313 [==============================] - 4s 3ms/step - loss: 0.0797 - accuracy: 0.9746
Epoch 4/25
1313/1313 [==============================] - 4s 3ms/step - loss: 0.0576 - accuracy: 0.9813
Epoch 5/25
1313/1313 [==============================] - 6s 5ms/step - loss: 0.0441 - accuracy: 0.9855
Epoch 6/25
1313/1313 [==============================] - 4s 3ms/step - loss: 0.0376 - accuracy: 0.9878
Epoch 7/25
1313/1313 [==============================] - 4s 3ms/step - loss: 0.0297 - accuracy: 0.9900
Epoch 8/25
1313/1313 [==============================] - 4s 3ms/step - loss: 0.0267 - accuracy: 0.9915
Epoch 9/25
1313/1313 [==============================] - 6s 4ms/step - loss: 0.0192 - accuracy: 0.9937
Epoch 10/25
1313/1313 [==============================] - 4s 3ms/step - loss: 0.021

In [ ]:
test=pd.read_csv('test.csv')
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [ ]:
test.drop(index=0)
test


pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27995       0       0       0       0       0       0       0       0       0   
27996       0       0       0       0       0       0       0       0       0   
27997       0       0       0       0       0       0       0       0       0   
27998       0       0       0       0       0       0       0       0       0   
27999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
27995       0  ...         0         0         0         0         0   
27996       0  ...         0         0         0         0         0   
27997       0  ...         0         0         0         0         0   
27998       0  ...         0         0         0         0         0   
27999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
27995         0         0         0         0         0  
27996         0         0         0         0         0  
27997         0         0         0         0         0  
27998         0         0         0         0         0  
27999         0         0         0         0         0  

[28000 rows x 784 columns]

In [ ]:
predict=model1.predict(test)

875/875 [==============================] - 2s 2ms/step


In [ ]:
predict.shape

(28000, 10)

In [ ]:
predict=predict.round()

In [ ]:
predict = tf.cast(predict, dtype=tf.int32)

In [ ]:
j=1
l=[]
for i in predict:
  print(i)
  indexes = tf.where(tf.equal(i, 1))
  print(indexes.numpy().squeeze())
  l.append([j,indexes.numpy().squeeze()])
  j=j+1

Streaming output truncated to the last 5000 lines.
tf.Tensor([1 0 0 0 0 0 0 0 0 0], shape=(10,), dtype=int32)
0
tf.Tensor([0 0 0 0 0 0 0 1 0 0], shape=(10,), dtype=int32)
7
tf.Tensor([0 1 0 0 0 0 0 0 0 0], shape=(10,), dtype=int32)
1
tf.Tensor([0 0 0 0 0 0 0 1 0 0], shape=(10,), dtype=int32)
7
tf.Tensor([0 1 0 0 0 0 0 0 0 0], shape=(10,), dtype=int32)
1
tf.Tensor([0 0 1 0 0 0 0 0 0 0], shape=(10,), dtype=int32)
2
tf.Tensor([0 0 0 0 0 0 0 1 0 0], shape=(10,), dtype=int32)
7
tf.Tensor([0 0 0 0 1 0 0 0 0 0], shape=(10,), dtype=int32)
4
tf.Tensor([1 0 0 0 0 0 0 0 0 0], shape=(10,), dtype=int32)
0
tf.Tensor([0 0 0 0 0 0 0 0 0 1], shape=(10,), dtype=int32)
9
tf.Tensor([0 0 0 0 0 0 1 0 0 0], shape=(10,), dtype=int32)
6
tf.Tensor([0 0 1 0 0 0 0 0 0 0], shape=(10,), dtype=int32)
2
tf.Tensor([0 0 0 0 0 0 1 0 0 0], shape=(10,), dtype=int32)
6
tf.Tensor([0 0 0 1 0 0 0 0 0 0], shape=(10,), dtype=int32)
3
tf.Tensor([0 0 1 0 0 0 0 0 0 0], shape=(10,), dtype=int32)
2
tf.Tensor([0 0 0 0 1 0 0 0 0 0], s

In [ ]:
exit=pd.DataFrame(l)
col=["ImageId","Label"]
exit.columns=col
exit.head()

ImageId Label
0        1     2
1        2     0
2        3     9
3        4     0
4        5     3

In [ ]:

from google.colab import files
exit.to_csv('sub.csv')
files.download('sub.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>